think_orm:
    default: 'mysql'
    connections:
        mysql:
            type: 'mysql'
            hostname: '%env(DB_HOSTNAME)%'
            hostport: '3306'
            username: '%env(DB_USERNAME)%'
            password: '%env(DB_PASSWORD)%'
            database: '%env(DB_DATABASE)%'
            trigger_sql: '%env(bool:DEBUG)%'
        sqlite:
            type: 'sqlite'
            hostname: '127.0.0.1'
            hostport: '3306'
            username: 'root'
            password: '123456'
            database: 'genealogy'
