one_think_orm:
    default: 'mysql'
    connections:
        mysql:
            type: 'mysql'
            hostname: '%env(DB_HOSTNAME)%'
            hostport: '3306'
            username: '%env(DB_USERNAME)%'
            password: '%env(DB_PASSWORD)%'
            database: '%env(DB_DATABASE)%'
            trigger_sql: '%env(bool:APP_DEBUG)%'
